name: Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Compile Gradle
        run: ./gradlew compileJava

      - name: Run Tests
        run: ./gradlew test